content:
 - name: films
   label: Films
   path: src/content/films
   type: collection
   view:
      fields: [title, date]
   fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: 1st Screening Date
        type: date
        description: must be in 'yyyy-mm-dd' format
      - name: time
        label: Time of Screening
        type: string
      - name: projectname
        label: Assoc. Project
        type: string
      - name: projectlink
        label: Link to Project
        type: string
      - name: genre
        label: Genre
        type: select
        options:
          multiple: true
          values: [Advert, Drama, Comedy, Thriller, Video Art, Other]
      - name: runtimehour
        label: Runtime (h)
        type: number
      - name: runtimemin
        label: Runtime (m)
        type: number
        options:
          max: 60
      - name: runtimesec
        label: Runtime (s)
        type: number
        options:
          max: 60
      - name: watchlink
        label: Video Link
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: slug
        label: Page ID
        type: string
        description: ID of each page. Must be in 'YYYY-title' pattern (e.g., 2024-artspace)
      - name: cover
        label: Poster
        type: image
        required: true
      - name: body
        label: Body
        type: rich-text
      - name: displaygallery
        label: Display Gallery
        type: boolean
        default: false
        required: true
      - name: gallery
        label: Gallery
        type: image
        required: false
        options:
          multiple: true
          path: projectgallery
      - name: displaygallerylink
        label: Display Gallery Link
        type: boolean
        default: false
        required: true
      - name: gallerylink
        label: Gallery Link
        type: string
        required: false
 - name: projects
   label: Projects
   path: src/content/projects
   type: collection
   view:
      fields: [title, datefrom]
   fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: datefrom
        label: Date of Activity (from)
        type: date
        description: must be in 'yyyy-mm-dd' format
        required: true
      - name: timefrom
        label: Time of Activity (from)
        type: string
      - name: dateto
        label: Date of Activity (to)
        type: string
        description: must be in 'yyyy-mm-dd' format
      - name: timeto
        label: Time of Activity (to)
        type: string
      - name: place
        label: Location
        type: string
        required: true
      - name: regisfrom
        label: Registration Period (from)
        type: string
      - name: registo
        label: Registration Period (to)
        type: string
      - name: regislink
        label: Registration Link
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: slug
        label: Page ID
        type: string
        description: ID of each page. Must be in 'YYYY-title' pattern (e.g., 2024-artspace)
      - name: cover
        label: Cover Image
        type: image
        required: true
      - name: body
        label: Body
        type: rich-text
      - name: displaygallery
        label: Display Gallery
        type: boolean
        default: false
        required: true
      - name: gallery
        label: Gallery
        type: image
        required: false
        options:
          multiple: true
          path: projectgallery
      - name: displaygallerylink
        label: Display Gallery Link
        type: boolean
        default: false
        required: true
      - name: gallerylink
        label: Gallery Link
        type: string
        required: false
 - name: team
   label: Team
   path: src/content/team/team.json
   type: file
   fields:
      - name: team
        type: object
        list: true
        fields:
        - name: ay
          label: Academic Year
          description: in ค.ศ.
          type: number
          options:
            min: 2023
            max: 2100
          required: true
        - name: nickname
          label: Nickname
          type: string
          required: true
        - name: name
          label: Name
          type: string
          required: true
        - name: si
          label: SI รุ่น
          type: number
          options:
            min: 132
            max: 200
          required: true
        - name: line
          label: สายรหัส
          type: string
          pattern: ^[0-9][0-9][0-9]$
          options:
            minlength: 3
            maxlength: 3
          required: true
        - name: position
          label: Position
          type: string
          required: true
        - name: cover
          label: Cover Image
          type: image
          required: true
        - name: id
          label: ID
          type: string
          description: use 'yy-no' pattern (e.g., 24-1), MUST be unique
          required: true
 - name: about
   label: About Page
   path: src/content/about.md
   type: file
   fields:
      - name: body
        label: Body
        type: rich-text

media:
- name: assets
  label: Assets
  input: src/assets
  output: ../../assets
  extensions: [png, jpeg, jpg]